// Generated by CoffeeScript 1.9.1
(function() {
  var recalc, spop, spush;

  spush = function() {
    var newtip, oldtip;
    oldtip = $('a.topic').first();
    if (oldtip.attr('id') === 'empty-stack') {
      oldtip.hide();
    } else {
      oldtip.removeClass('active');
    }
    newtip = $('a#ptype').clone();
    newtip.removeAttr('id');
    newtip.removeClass('hideme');
    newtip.addClass('active');
    newtip.text($('input').val());
    newtip.insertBefore(oldtip);
    $('input').val('');
    return recalc();
  };

  spop = function() {
    var doomed, empty_stack, hotshot;
    doomed = $('a.topic.active').first();
    hotshot = $('a.topic').not('.active').first();
    empty_stack = hotshot.attr('id') === 'empty-stack';
    doomed.removeClass('active');
    doomed.addClass('disabled');
    if (!empty_stack) {
      hotshot.addClass('active');
      doomed.slideUp(300, function() {
        return this.remove();
      });
    }
    if (empty_stack) {
      doomed.remove();
      hotshot.fadeIn();
    }
    return recalc();
  };

  recalc = function() {
    $('a.topic').unbind();
    return $('a.topic').not('#ptype').not('#empty-stack').click(spop);
  };

  $(document).ready(function() {
    $('#push').click(spush);
    $('input').focus();
    $('input').select();
    $('input').keyup(function(event) {
      if (event.which === 13 && $('input').val() !== '') {
        spush();
      }
      if (event.which === 0x2e && $('input').val() === '') {
        return spop();
      }
    });
    return recalc();
  });

}).call(this);
