// Generated by CoffeeScript 1.7.1
(function() {
  var recalc, spop, spush;

  spush = function() {
    var ptype, topel;
    topel = $('a.topic').first();
    if (topel.id === 'empty-stack') {
      topel.addClass('hideme');
    } else {
      topel.removeClass('active');
    }
    ptype = $('a#ptype').clone();
    ptype.removeAttr('id');
    ptype.removeClass('hideme');
    ptype.addClass('active');
    ptype.text($('input').val());
    ptype.insertBefore(topel);
    $('input').val('');
    return recalc();
  };

  spop = function() {
    var doomed, topel;
    doomed = $('a.topic.active').first();
    doomed.remove();
    topel = $('a.topic').first();
    if (topel.id === 'empty-stack') {
      topel.removeClass('hideme');
    } else {
      topel.addClass('active');
    }
    return recalc();
  };

  recalc = function() {
    $('a.topic').unbind();
    return $('a.topic.active').first().click(spop);
  };

  $(document).ready(function() {
    $('#push').click(spush);
    $('input').keyup(function(event) {
      if (event.which === 13) {
        spush();
      }
      if (event.which === 0x2e && $('input').val === '') {
        return spop();
      }
    });
    return recalc();
  });

}).call(this);
